/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package program;

import com.alexmerz.graphviz.objects.Edge;
import com.alexmerz.graphviz.objects.Graph;
import com.alexmerz.graphviz.objects.Id;
import com.alexmerz.graphviz.objects.Node;
import com.alexmerz.graphviz.objects.PortNode;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;
import java.awt.image.ImageProducer;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.AbstractButton;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import sun.misc.IOUtils;

/**
 *
 * @author Darek
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Okno
     */
    /*
    dataIdList, graphs, lastNodes, parallelNodesHistory, 
                                        parallelPathsHistory,  parallelNodes, parallelPaths, 
                                        selectedDiseases, currentImages, questionsTabbedPane, 
                                        imagesTabbedPane
    */
  
    private ArrayList<JCheckBox> checkBoxGroup;
    private MainClass mainClass;
    public ArrayList<JCheckBox> getCheckBoxGroup()
    {
        return checkBoxGroup;
    }
    public Window() {
        initComponents();
        checkBoxGroup = new ArrayList<JCheckBox>();
        mainClass = new MainClass();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        conflictsScrollPane.setVisible(false);
        conflictsTextArea.setEditable(false);
        conflictsTextArea.setLineWrap(true);
        conflictsLabel.setVisible(false);
        selectedPathsLabel.setVisible(false);
        resultsLabel.setVisible(false);
        File directory = new File("algorytmy");
        File[] listOfFiles = directory.listFiles(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.toLowerCase().endsWith(".dot");
            }
        });
        for(int i=0;i<listOfFiles.length;i++)
        {
            JCheckBox checkBox = new JCheckBox();
            checkBox.setText(listOfFiles[i].getName().substring(0, listOfFiles[i].getName().lastIndexOf('.')));
            checkBoxGroup.add(checkBox);
            diseasesPanel.add(checkBox);
        }
    }
    public JTabbedPane getQuestionsTabbedPane(){
        return questionsTabbedPane;
    }
    public JTabbedPane getImagesTabbedPane(){
        return imagesTabbedPane;
    }
    public void setResults(ArrayList<String[]> foundConflicts, 
            ArrayList<ArrayList<String[]>> executedInteractions, ArrayList<ArrayList<ArrayList<String>>> therapies)
    {
        mainClass.setResults(foundConflicts, executedInteractions, therapies, 
                resultsTabbedPane, conflictsTextArea, conflictsScrollPane, 
            conflictsLabel, selectedPathsLabel, resultsLabel, 
            mainTabbedPane, graphsResultsTabbedPane);
    }
   
    private void removeFiles()
    {
        File directory = new File("grafy");
        File[] listOfFiles = directory.listFiles(new FilenameFilter() {
            @Override
            public boolean accept(File dir, String name) {
                return name.toLowerCase().endsWith(".dot")
                     ||name.toLowerCase().endsWith(".png");
            }
        });
        for(File f:listOfFiles)
        {
            f.delete();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        selectDiseases = new javax.swing.JLabel();
        next = new javax.swing.JButton();
        diseasesPanel = new javax.swing.JPanel();
        disease = new javax.swing.JLabel();
        imagesTabbedPane = new javax.swing.JTabbedPane();
        mainTabbedPane = new javax.swing.JTabbedPane();
        questionsTabbedPane = new javax.swing.JTabbedPane();
        resultsPanel = new javax.swing.JPanel();
        resultsTabbedPane = new javax.swing.JTabbedPane();
        conflictsScrollPane = new javax.swing.JScrollPane();
        conflictsTextArea = new javax.swing.JTextArea();
        selectedPathsTabbedPane = new javax.swing.JTabbedPane();
        conflictsLabel = new javax.swing.JLabel();
        selectedPathsLabel = new javax.swing.JLabel();
        resultsLabel = new javax.swing.JLabel();
        graphsResultsTabbedPane = new javax.swing.JTabbedPane();
        selectDiseasesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System wspomagający stosowanie procedur klinicznych");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        selectDiseases.setText("Wybierz choroby:");

        next.setLabel("Dalej");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        diseasesPanel.setLayout(new java.awt.GridLayout(0, 1));

        disease.setText(" ");

        mainTabbedPane.addTab("Pytania", questionsTabbedPane);

        resultsTabbedPane.setMinimumSize(new java.awt.Dimension(500, 5));

        conflictsTextArea.setColumns(20);
        conflictsTextArea.setRows(5);
        conflictsTextArea.setMinimumSize(new java.awt.Dimension(500, 16));
        conflictsScrollPane.setViewportView(conflictsTextArea);

        selectedPathsTabbedPane.setMinimumSize(new java.awt.Dimension(500, 5));

        conflictsLabel.setText("Konflikty:");

        selectedPathsLabel.setText("Wybrane ścieżki:");

        resultsLabel.setText("Wyniki:");

        javax.swing.GroupLayout resultsPanelLayout = new javax.swing.GroupLayout(resultsPanel);
        resultsPanel.setLayout(resultsPanelLayout);
        resultsPanelLayout.setHorizontalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultsTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(conflictsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(selectedPathsTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(resultsPanelLayout.createSequentialGroup()
                        .addGroup(resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(conflictsLabel)
                            .addComponent(selectedPathsLabel)
                            .addComponent(resultsLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultsPanelLayout.setVerticalGroup(
            resultsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultsPanelLayout.createSequentialGroup()
                .addComponent(selectedPathsLabel)
                .addGap(8, 8, 8)
                .addComponent(selectedPathsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(conflictsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conflictsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(resultsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        mainTabbedPane.addTab("Wyniki", resultsPanel);
        mainTabbedPane.addTab("Grafy", graphsResultsTabbedPane);

        selectDiseasesButton.setText("Wybierz choroby");
        selectDiseasesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDiseasesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selectDiseases)
                    .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diseasesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(next)
                                .addGap(44, 44, 44)
                                .addComponent(selectDiseasesButton)))))
                .addGap(114, 114, 114)
                .addComponent(imagesTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(557, 557, 557))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(disease)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(disease)
                        .addGap(61, 61, 61)
                        .addComponent(imagesTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(selectDiseases)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diseasesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(next)
                            .addComponent(selectDiseasesButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(543, 543, 543))
        );

        selectDiseases.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        mainClass.buttonClick(selectDiseases, diseasesPanel, 
            imagesTabbedPane, selectedPathsTabbedPane, 
            this);
    }//GEN-LAST:event_nextActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        removeFiles();
    }//GEN-LAST:event_formWindowClosing

    private void selectDiseasesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDiseasesButtonActionPerformed
       selectDiseases.setVisible(true);
       diseasesPanel.setVisible(true); 
       selectedPathsLabel.setVisible(false);
       selectedPathsTabbedPane.removeAll();
       conflictsLabel.setVisible(false);
       conflictsScrollPane.setVisible(false);
       resultsLabel.setVisible(false);
       resultsTabbedPane.removeAll();
       questionsTabbedPane.removeAll();
       graphsResultsTabbedPane.removeAll();
       imagesTabbedPane.removeAll();
       mainClass.setStartProgram(true);
       for(JCheckBox checkBox:checkBoxGroup)
       {
           checkBox.setSelected(false);
       }
    }//GEN-LAST:event_selectDiseasesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel conflictsLabel;
    private javax.swing.JScrollPane conflictsScrollPane;
    private javax.swing.JTextArea conflictsTextArea;
    private javax.swing.JLabel disease;
    private javax.swing.JPanel diseasesPanel;
    private javax.swing.JTabbedPane graphsResultsTabbedPane;
    private javax.swing.JTabbedPane imagesTabbedPane;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JButton next;
    private javax.swing.JTabbedPane questionsTabbedPane;
    private javax.swing.JLabel resultsLabel;
    private javax.swing.JPanel resultsPanel;
    private javax.swing.JTabbedPane resultsTabbedPane;
    private javax.swing.JLabel selectDiseases;
    private javax.swing.JButton selectDiseasesButton;
    private javax.swing.JLabel selectedPathsLabel;
    private javax.swing.JTabbedPane selectedPathsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
